version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: booking-management-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//db:1521/orcl
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: Hongngoc1234@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: Hongngoc1234@
      ORACLE_DATABASE: orcl